Repository SoboonSoboon/soboon-design-system, pull requests merged in 2025-10, with the labels that each got.

#34 Feat/card/#27
  src/components/Card.tsx
  src/index.css
  src/stories/Card.stories.tsx
Labels: ✨ Feature

#43 rename: 폴더 구조 정리
  README.md
  src/components/Atoms/Badge/Badge.tsx
  src/components/Atoms/Badge/index.ts
  src/components/Atoms/Chip/Chip.tsx
  src/components/Atoms/Chip/index.ts
  src/components/Atoms/DateSortToggle/DateSortToggle.tsx
  src/components/Atoms/DateSortToggle/index.ts
  src/components/Atoms/Label/Label.tsx
  src/components/Atoms/Label/index.ts
  src/components/Atoms/TextInput/TextInput.tsx
  src/components/Atoms/TextInput/index.ts
  src/components/Atoms/Textarea/Textarea.tsx
  src/components/Atoms/Textarea/index.ts
  src/components/Atoms/index.ts
  src/components/Molecules/Card/Card.tsx
  src/components/Molecules/Card/index.ts
  src/components/Molecules/Dropdown/Dropdown.tsx
  src/components/Molecules/Dropdown/index.ts
  src/components/Molecules/index.ts
  src/stories/Atoms/Badge.stories.tsx
  src/stories/Atoms/Chip.stories.tsx
  src/stories/Atoms/DateSortToggle.stories.tsx
  src/stories/Atoms/Label.stories.ts
  src/stories/Atoms/TextInput.stories.tsx
  src/stories/Atoms/Textarea.stories.tsx
  src/stories/Button.stories.ts
  src/stories/Button.tsx
  src/stories/Dropdown.stories.tsx
  src/stories/Header.stories.ts
  src/stories/Header.tsx
  src/stories/Molecules/Card.stories.tsx
  src/stories/Molecules/Dropdown.stories.tsx
  src/stories/Page.stories.ts
  src/stories/Page.tsx
  src/stories/TextInput.stories.tsx
  src/stories/Textarea.stories.tsx
  src/stories/button.css
  src/stories/header.css
  src/stories/page.css
Labels: 🛠️ Refactor

#40 fix: tsconfig 에러 수정
  tsconfig.app.json
  tsconfig.node.json
Labels: 🐞 BugFix

#39 fix: Pretendard font error
  index.html
  src/index.css
Labels: 🐞 BugFix

#52 setting: npm 배포를 위한 세팅
  .github/workflows/npm-publish.yml
  package-lock.json
  package.json
  setupTests.js
  src/components/Atoms/DateSortToggle/DateSortToggle.tsx
  src/components/Atoms/DateSortToggle/index.ts
  src/components/Atoms/index.ts
  src/components/Molecules/Card/Card.tsx
  src/components/Molecules/Card/index.ts
  src/components/Molecules/index.ts
  src/index.tsx
  src/main.tsx
  src/output.css
  tsconfig.app.json
  tsconfig.json
  tsconfig.node.json
  tsconfig.tsbuildinfo
  vite.config.d.ts
  vite.config.ts
Labels: ⚙️ Setting

#53 release: dev to main
  .github/workflows/npm-publish.yml
  index.html
  package-lock.json
  package.json
  setupTests.js
  src/components/Atoms/Button.tsx
  src/components/Atoms/DateSortToggle/DateSortToggle.tsx
  src/components/Atoms/DateSortToggle/index.ts
  src/components/Atoms/index.ts
  src/components/Molecules/Card/Card.tsx
  src/components/Molecules/Card/index.ts
  src/components/Molecules/Header/Header.tsx
  src/components/Molecules/index.ts
  src/components/atoms/Logo.tsx
  src/components/atoms/ProfileImg.tsx
  src/index.css
  src/index.tsx
  src/main.tsx
  src/output.css
  src/stories/Button.stories.ts
  src/stories/Molecules/Header.stories.ts
  src/stories/Page.tsx
  tsconfig.app.json
  tsconfig.json
  tsconfig.node.json
  tsconfig.tsbuildinfo
  vite.config.d.ts
  vite.config.ts
Labels: 🚀 Release

#59 fix: npm 배포 이슈 해결
  .github/workflows/npm-publish.yml
  package.json
  vite.config.ts
Labels: 🐞 BugFix

#62 feat: main 브랜치에 배포시 자동 버전 업그레이트 코드 추가 @misung-dev
  .github/workflows/npm-publish.yml
  package-lock.json
  package.json
Labels: 🐞 BugFix, ✨ Feature

#66 release: dev to main
  .github/workflows/npm-publish.yml
Labels: 🚀 Release
